# Site settings
title: OpenIFun: Open Data Science for Input Functions for PET parametric imaging
author:
  name: Guobao Wang
  email: your-email@domain.com
description: "OpenIFun is a part of the OpenData effort from the Open Kinetic Modeling Initiative (www.openkmi.org)."

# Build settings
remote_theme: jekyll/minima
